# Generated by Django 5.0 on 2025-12-07 19:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBeca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('monto_mensual', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duracion_meses', models.IntegerField(help_text='Duración en meses de la beca', validators=[django.core.validators.MinValueValidator(1)])),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Beca',
                'verbose_name_plural': 'Tipos de Beca',
                'db_table': 'tipo_beca',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('gestion', models.CharField(help_text='Ej: 2025-1, 2025-2', max_length=10)),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha de inicio de postulaciones')),
                ('fecha_cierre', models.DateTimeField(help_text='Fecha de cierre de postulaciones')),
                ('fecha_publicacion_resultados', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADA', 'Publicada'), ('PAUSADA', 'Pausada'), ('CERRADA', 'Cerrada'), ('FINALIZADA', 'Finalizada')], default='BORRADOR', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convocatorias_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
                'db_table': 'convocatoria',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CriterioEvaluacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('ACADEMICO', 'Académico'), ('SOCIOECONOMICO', 'Socioeconómico'), ('OTRO', 'Otro')], max_length=20)),
                ('ponderacion', models.IntegerField(help_text='Peso del criterio en porcentaje (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('orden', models.IntegerField(default=0)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='convocatorias.convocatoria')),
            ],
            options={
                'verbose_name': 'Criterio de Evaluación',
                'verbose_name_plural': 'Criterios de Evaluación',
                'db_table': 'criterio_evaluacion',
                'ordering': ['convocatoria', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='RequisitoDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('CERTIFICADO_NOTAS', 'Certificado de Notas'), ('CARTA_MOTIVACION', 'Carta de Motivación'), ('DECLARACION_JURADA', 'Declaración Jurada'), ('COMPROBANTE_INGRESOS', 'Comprobante de Ingresos'), ('FOTOCOPIA_CI', 'Fotocopia de CI'), ('OTRO', 'Otro')], max_length=30)),
                ('obligatorio', models.BooleanField(default=True)),
                ('formato_permitido', models.CharField(default='PDF', help_text='Formatos permitidos separados por coma. Ej: PDF,JPG,PNG', max_length=100)),
                ('tamano_maximo_mb', models.IntegerField(default=5, help_text='Tamaño máximo en MB', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('orden', models.IntegerField(default=0)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='convocatorias.convocatoria')),
            ],
            options={
                'verbose_name': 'Requisito Documental',
                'verbose_name_plural': 'Requisitos Documentales',
                'db_table': 'requisito_documento',
                'ordering': ['convocatoria', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='CupoConvocatoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facultad', models.CharField(help_text='Nombre de la facultad', max_length=200)),
                ('cantidad_cupos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cupos_asignados', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupos', to='convocatorias.convocatoria')),
                ('tipo_beca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='convocatorias.tipobeca')),
            ],
            options={
                'verbose_name': 'Cupo de Convocatoria',
                'verbose_name_plural': 'Cupos de Convocatoria',
                'db_table': 'cupo_convocatoria',
                'unique_together': {('convocatoria', 'tipo_beca', 'facultad')},
            },
        ),
    ]
