# Generated by Django 5.0 on 2025-12-07 20:31

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipobeca',
            options={'ordering': ['codigo'], 'verbose_name': 'Tipo de Beca', 'verbose_name_plural': 'Tipos de Beca'},
        ),
        migrations.AddField(
            model_name='tipobeca',
            name='codigo',
            field=models.CharField(default='TEMP', help_text='Código interno institucional (ej: BECA-ALI, BECA-EST)', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='tipobeca',
            name='es_pago_directo',
            field=models.BooleanField(default=True, help_text='False para Beca Alimentación (comedor), True para pagos monetarios'),
        ),
        migrations.AddField(
            model_name='tipobeca',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tipobeca',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tipobeca',
            name='requiere_informe_mensual',
            field=models.BooleanField(default=True, help_text='Indica si el becario debe enviar informes mensuales de actividades'),
        ),
        migrations.AddField(
            model_name='tipobeca',
            name='requisitos_especificos',
            field=models.TextField(blank=True, help_text='Requisitos específicos adicionales para este tipo de beca'),
        ),
        migrations.AlterField(
            model_name='tipobeca',
            name='duracion_meses',
            field=models.IntegerField(default=6, help_text='Duración en meses (1 semestre = 6 meses)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tipobeca',
            name='monto_mensual',
            field=models.DecimalField(decimal_places=2, help_text='Monto mensual en bolivianos', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
