# Generated by Django 5.0 on 2025-12-07 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0003_ajustar_criterios_y_requisitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterioevaluacion',
            name='ponderacion',
            field=models.FloatField(help_text='Peso del criterio en porcentaje (0-100, puede tener decimales)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='criterioevaluacion',
            name='tipo_dato',
            field=models.CharField(default='NUMERICO', help_text='Tipo de dato: NUMERICO, TEXTO, BOOLEAN, FECHA, ARCHIVO', max_length=20),
        ),
    ]
