# Generated by Django 5.0 on 2025-12-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0004_alter_criterioevaluacion_ponderacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipobeca',
            name='tipo_evaluacion',
            field=models.CharField(choices=[('DEPENDENCIA_70_30', 'Becas de Dependencia (70% Socio + 30% Académico)'), ('MERITO_100', 'Mérito Académico (100% Académico)')], default='DEPENDENCIA_70_30', help_text='Tipo de evaluación según categoría de beca (Reglamento oficial)', max_length=20),
        ),
        migrations.DeleteModel(
            name='CriterioEvaluacion',
        ),
    ]
