# Generated by Django 5.0 on 2025-12-07 21:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convocatorias', '0004_alter_criterioevaluacion_ponderacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('RECEPCIONADO', 'Recepcionado'), ('EN_REVISION', 'En Revisión'), ('OBSERVADO', 'Observado'), ('EVALUADO', 'Evaluado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20)),
                ('puntaje_socioeconomico', models.FloatField(blank=True, help_text='Puntaje socioeconómico (máx. 70 pts)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('puntaje_academico', models.FloatField(blank=True, help_text='Puntaje académico (máx. 30 pts)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('puntaje_total', models.FloatField(blank=True, help_text='Puntaje total (máx. 100 pts)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha_evaluacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postulaciones', to='convocatorias.convocatoria')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postulaciones', to=settings.AUTH_USER_MODEL)),
                ('evaluado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulaciones_evaluadas', to=settings.AUTH_USER_MODEL)),
                ('tipo_beca_solicitada', models.ForeignKey(help_text='Tipo de beca a la que postula', on_delete=django.db.models.deletion.PROTECT, to='convocatorias.tipobeca')),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'db_table': 'postulacion',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('convocatoria', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='FormularioSocioeconomico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_miembros_familia', models.IntegerField(help_text='Número total de miembros de la familia', validators=[django.core.validators.MinValueValidator(1)])),
                ('numero_dependientes', models.IntegerField(help_text='Número de personas que dependen económicamente', validators=[django.core.validators.MinValueValidator(0)])),
                ('ingreso_familiar_mensual', models.DecimalField(decimal_places=2, help_text='Ingreso familiar total mensual en Bs.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ingreso_per_capita', models.DecimalField(decimal_places=2, help_text='Ingreso per cápita (ingreso total / miembros familia)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gasto_vivienda_mensual', models.DecimalField(decimal_places=2, help_text='Gasto mensual en vivienda (alquiler/servicios)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gasto_alimentacion_mensual', models.DecimalField(decimal_places=2, help_text='Gasto mensual en alimentación', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gasto_educacion_mensual', models.DecimalField(decimal_places=2, help_text='Gasto mensual en educación', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gasto_salud_mensual', models.DecimalField(decimal_places=2, help_text='Gasto mensual en salud', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('otros_gastos_mensual', models.DecimalField(decimal_places=2, help_text='Otros gastos mensuales', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo_vivienda', models.CharField(choices=[('PROPIA', 'Propia'), ('ALQUILADA', 'Alquilada'), ('PRESTADA', 'Prestada'), ('ANTICRETICO', 'Anticrético')], default='PROPIA', max_length=50)),
                ('tiene_discapacidad', models.BooleanField(default=False)),
                ('es_madre_soltera', models.BooleanField(default=False)),
                ('es_padre_soltero', models.BooleanField(default=False)),
                ('proviene_area_rural', models.BooleanField(default=False)),
                ('observaciones_adicionales', models.TextField(blank=True, help_text='Información adicional relevante sobre situación socioeconómica')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('postulacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formulario_socioeconomico', to='postulaciones.postulacion')),
            ],
            options={
                'verbose_name': 'Formulario Socioeconómico',
                'verbose_name_plural': 'Formularios Socioeconómicos',
                'db_table': 'formulario_socioeconomico',
            },
        ),
        migrations.CreateModel(
            name='FormularioAcademico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('promedio_general', models.DecimalField(decimal_places=2, help_text='Promedio académico general', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('semestre_actual', models.IntegerField(help_text='Semestre que está cursando actualmente', validators=[django.core.validators.MinValueValidator(1)])),
                ('materias_aprobadas', models.IntegerField(help_text='Total de materias aprobadas', validators=[django.core.validators.MinValueValidator(0)])),
                ('materias_reprobadas', models.IntegerField(default=0, help_text='Total de materias reprobadas', validators=[django.core.validators.MinValueValidator(0)])),
                ('participa_actividades_universitarias', models.BooleanField(default=False, help_text='Participa en actividades extracurriculares universitarias')),
                ('descripcion_actividades', models.TextField(blank=True, help_text='Descripción de actividades extracurriculares')),
                ('participa_proyectos_investigacion', models.BooleanField(default=False, help_text='Participa en proyectos de investigación')),
                ('descripcion_investigacion', models.TextField(blank=True, help_text='Descripción de proyectos de investigación')),
                ('tiene_reconocimientos_academicos', models.BooleanField(default=False, help_text='Tiene reconocimientos académicos')),
                ('descripcion_reconocimientos', models.TextField(blank=True, help_text='Descripción de reconocimientos académicos')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('postulacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formulario_academico', to='postulaciones.postulacion')),
            ],
            options={
                'verbose_name': 'Formulario Académico',
                'verbose_name_plural': 'Formularios Académicos',
                'db_table': 'formulario_academico',
            },
        ),
        migrations.CreateModel(
            name='DocumentoPostulacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(help_text='Ruta en MinIO o sistema de archivos', max_length=500)),
                ('tipo_mime', models.CharField(max_length=100)),
                ('tamano_bytes', models.BigIntegerField(help_text='Tamaño del archivo en bytes', validators=[django.core.validators.MinValueValidator(0)])),
                ('hash_sha256', models.CharField(help_text='Hash SHA256 para verificación de integridad', max_length=64)),
                ('version', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('observaciones_revision', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('documento_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_posteriores', to='postulaciones.documentopostulacion')),
                ('requisito', models.ForeignKey(help_text='Requisito documental que cumple', on_delete=django.db.models.deletion.PROTECT, to='convocatorias.requisitodocumento')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_revisados', to=settings.AUTH_USER_MODEL)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='postulaciones.postulacion')),
            ],
            options={
                'verbose_name': 'Documento de Postulación',
                'verbose_name_plural': 'Documentos de Postulación',
                'db_table': 'documento_postulacion',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
