# Generated by Django 5.0 on 2025-12-08 00:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('puntaje_socioeconomico', models.DecimalField(decimal_places=2, help_text='Puntaje socioeconómico calculado (0-70 para dependencia, 0 para excelencia)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('puntaje_academico', models.DecimalField(decimal_places=2, help_text='Puntaje académico calculado (0-30 para dependencia, 0-100 para excelencia)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('puntaje_total', models.DecimalField(decimal_places=2, help_text='Puntaje total final (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ponderacion_socio_aplicada', models.IntegerField(help_text='Ponderación socioeconómica aplicada según tipo de beca', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ponderacion_academico_aplicada', models.IntegerField(help_text='Ponderación académica aplicada según tipo de beca', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tipo_evaluacion_aplicado', models.CharField(help_text='Tipo de evaluación aplicado (DEPENDENCIA_70_30 o MERITO_100)', max_length=20)),
                ('explicacion_shap', models.JSONField(help_text='Valores SHAP para explicar la decisión del modelo IA')),
                ('features_importantes', models.JSONField(blank=True, help_text='Top features que influyeron en el puntaje', null=True)),
                ('recomendacion', models.CharField(choices=[('APROBADO', 'Recomendado para Aprobación'), ('RECHAZADO', 'Recomendado para Rechazo'), ('REVISION', 'Requiere Revisión Manual')], help_text='Recomendación automática del sistema IA', max_length=20)),
                ('confianza', models.DecimalField(blank=True, decimal_places=2, help_text='Nivel de confianza de la predicción (0-100%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('modelo_version', models.CharField(default='v1.0', help_text='Versión del modelo IA utilizado', max_length=50)),
                ('tiempo_procesamiento_ms', models.IntegerField(blank=True, help_text='Tiempo de procesamiento en milisegundos', null=True)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('evaluado_por_usuario', models.ForeignKey(blank=True, help_text='Usuario que solicitó la evaluación IA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_ia_iniciadas', to=settings.AUTH_USER_MODEL)),
                ('postulacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_ia', to='postulaciones.postulacion')),
            ],
            options={
                'verbose_name': 'Evaluación IA',
                'verbose_name_plural': 'Evaluaciones IA',
                'db_table': 'evaluacion_ia',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
    ]
