# Generated by Django 5.0 on 2025-12-08 04:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulaciones', '0002_evaluacionia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoBeca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('INFORME_ACADEMICO', 'Informe Académico'), ('CERTIFICADO_NOTAS', 'Certificado de Notas'), ('COMPROBANTE_PAGO', 'Comprobante de Pago'), ('OTRO', 'Otro')], default='INFORME_ACADEMICO', max_length=30)),
                ('titulo', models.CharField(help_text='Título del documento de seguimiento', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o comentarios del estudiante')),
                ('documento', models.FileField(help_text='Archivo de seguimiento', upload_to='seguimientos/%Y/%m/')),
                ('estado', models.CharField(choices=[('PENDIENTE_REVISION', 'Pendiente de Revisión'), ('REVISADO', 'Revisado'), ('OBSERVADO', 'Observado')], default='PENDIENTE_REVISION', max_length=20)),
                ('observaciones_responsable', models.TextField(blank=True, help_text='Observaciones del responsable')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('postulacion', models.ForeignKey(help_text='Postulación aprobada que se está siguiendo', on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos', to='postulaciones.postulacion')),
                ('revisado_por', models.ForeignKey(blank=True, help_text='Responsable que revisó el seguimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento de Beca',
                'verbose_name_plural': 'Seguimientos de Becas',
                'db_table': 'seguimiento_beca',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
