# Generated by Django 5.0 on 2025-12-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulaciones', '0003_seguimientobeca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Bandera de edición manual
        migrations.AddField(
            model_name='evaluacionia',
            name='editado_manualmente',
            field=models.BooleanField(
                default=False,
                help_text='Indica si los puntajes fueron modificados manualmente después de la evaluación IA'
            ),
        ),
        
        # Puntajes originales de la IA (para auditoría)
        migrations.AddField(
            model_name='evaluacionia',
            name='puntajes_originales_ia',
            field=models.JSONField(
                null=True,
                blank=True,
                help_text='Puntajes originales calculados por la IA antes de edición manual (si aplica)'
            ),
        ),
        
        # Fecha de última edición
        migrations.AddField(
            model_name='evaluacionia',
            name='fecha_ultima_edicion',
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text='Fecha de la última edición manual de puntajes'
            ),
        ),
        
        # Usuario que editó
        migrations.AddField(
            model_name='evaluacionia',
            name='editado_por_usuario',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='evaluaciones_ia_editadas',
                to=settings.AUTH_USER_MODEL,
                help_text='Usuario que realizó la última edición manual'
            ),
        ),
    ]
